### PR TITLE
Feature/fix parallel circuits

### PR DESCRIPTION
**Pull request by srichmond**

### CODE REVIEW

**Comment by pjm17971** [comment]
Ok, but I don't think the middle connection needs to be special cased like this. The old code just did this:
```
        if (numBranches > 0) {
            offset = - (numBranches - 1) * 0.5 - 1;
            _.each(branches, function(circuit) {
                offset += 1;
                elements.push(
                    <Connection width={width}
                                key={circuit.id}
                                circuit={circuit}
                                circuitTypes={self.props.circuitTypes}
                                offset={offset}/>
                );
            });
```
Where offset could be multiplied by something to get the y position.
Do you think you could make this simple?

**Comment by srichmond** [comment]
The way that the offset works was changed in the underlying <Connection> code, which is why I couldn't get this to work the same as before, but I will try and simplify.  

We are taking advantage of the position prop in the connection code now which adds an angle offset from the center.

**Comment by srichmond** [comment]
Ok - cleaned it up to reflect the changes requested.

**Comment by pjm17971** [comment]
+1. Thanks for making those changes.

**Pull request merged**
